### ISSUE TITLE
Dasherized type names when requesting resources results in errors

### ISSUE THREAD

**Issue by dalane** [fortunejs/fortune-json-api#34]
I'm using Ember's JSONAPI serializer and it dasherizes type names when making requests (e.g. "myType" is sent as "my-type"). This is causing a couple of errors...

The first error is when requests are made to "/my-type" or "/my-type/id". This returns a not found error stating that "my-type" is not a valid type.

The second error is an internal error that occurs when I make a request to filter resources such as "/my-type?filter[user]=somevalue". Logging this error returns the following type error:

```
TypeError: Cannot use 'in' operator to search for 'user' in undefined
    at JsonApiSerializer.attachQueries (/Projects/Api/node_modules/fortune-json-api/lib/helpers.js:315:22)
    at JsonApiSerializer.initializeContext (/Projects/Api/node_modules/fortune-json-api/lib/helpers.js:95:17)
    at JsonApiSerializer.processRequest (/Projects/Api/node_modules/fortune-json-api/lib/index.js:74:30)
    at /Projects/Api/node_modules/fortune/lib/net/http_server.js:237:10
    at tryCatcher (/Projects/Api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Projects/Api/node_modules/bluebird/js/release/promise.js:510:31)

    at Promise._settlePromise (/Projects/Api/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Projects/Api/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Projects/Api/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Projects/Api/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Projects/Api/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Projects/Api/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Debugging the error it appears that the variable "fields" on line 315 is undefined. This appears to be due to the fact that the value for request.type passed to attachQueries is "my-type" so the assignment "const fields = recordTypes[type]" at line 280 is returning an undefined value.

To cater for the dasherized type names sent by Ember could the inflection of the type name also camelize type names and not just pluralize?

**Comment by gr0uch** [comment]
Yeah, it should actually pluralize and dasherize, it currently handles pluralizing only. It should be an easy fix.

**Comment by gr0uch** [comment]
Should be fixed in https://github.com/fortunejs/fortune-json-api/commit/4ff3c09153c9580042c0a983cd1a64ca167a75d2.

**Comment by dalane** [comment]
Thanks for looking at this. Sorry it's taken a while to respond.

Unless I'm doing something wrong I'm still getting 404 not found errors on dasherized resource names (see https://github.com/dalane/test-fortune).

I am entertained with the comments you've included in index.js and share your frustration. This is why we had the discussion on the fortune repo about having a hook/transform on the find method. Trying to implement authorization on records is a bit of a challenge with so many different ways of getting to the data...

**Comment by gr0uch** [comment]
Hmm, I think this may be missing a few tests for the inflections. It is very frustrating to deal with the de facto recommendations.

Actually authorization shouldn't be different no matter how records are accessed. i.e.:

``` js
function output (context, record) {
  if (!authorizationCondition)
    throw new fortune.errors.UnauthorizedError('...')

  return record
}
```

**Comment by gr0uch** [comment]
This should be fixed in this commit: https://github.com/fortunejs/fortune-json-api/commit/2ce448881a0971c86ed2526255e7342124251457

I published a patch version. Let me know if it's still broken.

**Comment by cahva** [comment]
Came a cross this problem today when doing include with fields parameter. I don't think its the same reason what you guys talked about.

For example:
``` 
GET /users/user1?include=foo&fields[foo]=bar
```

The line with that error is this:
```javascript
if (!(sparseType in request.includeOptions))
```

Theres no such thing as `includeOptions` anywhere in the base fortune repo or elsewhere, only on this helper file in this repo. There is this change in the changelog in fortune base repo:
https://github.com/fortunejs/fortune/blob/master/doc/CHANGELOG.md#320-2016-02-28

```
Deprecation: removed includeOptions, moved to include.
```

I forked this repo and created a test to confirm this behaviour:
https://github.com/cahva/fortune-json-api/commit/6bad992eb742a8cdb694df83c2eb9c462baee2aa

**Comment by gr0uch** [comment]
A patch has been released. Here is the commit: https://github.com/fortunejs/fortune-json-api/commit/a9289e904c50bae0a6427f98b3c203e79fc46188

I'm not sure about supporting `fields` for included records because the format does not consider deeply nested includes.
