### ISSUE TITLE
Questions about filtering

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune-json-api#40]
### 1. Filter by containing value in array
Currently I cannot make filtering work for my resource. It contains `keywords` array of strings. Do I need to use specific syntax in query param? 

Current request looks like: `http://localhost:9876/v1/articles/?include=author,category&filter[keywords]=eighties`.

### 2. Is it possible to filter by related resources keys?
In my example every post has relation with category but trying to filter is not successful:
- by id `http://localhost:9876/v1/articles/?include=author,category&filter[category]= b68b3197aa83b3b5b47c10b09566588b` => does nothing
- by title `http://localhost:9876/v1/articles/?include=author,category&filter[category.title]=музыка` => returns 400 error `"The field \"category.title\" is non-existent."`.

**Comment by gr0uch** [comment]
Look at the tests first: https://github.com/fortunejs/fortune-json-api/blob/01644284ddeec836dcfd12b7fe2432ca557b99ad/test/index.js#L234

Also I added corresponding adapter tests, it should be working fine: https://github.com/fortunejs/fortune/blob/42911c0ba28bdf4398e88b4c3a20e38b163e459a/test/unit/adapter.js#L215-L225

Keep in mind that `filter` is completely unspecified by JSON:API so every implementation will do it differently. The syntax `filter[category.title]` is incorrect, it can only work like `filter[category]`.

**Comment by voronianski** [comment]
@daliwali 

- there are no example in tests for filtering by nested object key (e.g. `category.title` or `category.id`)
- pls try to add example for filtering by `nicknames` https://github.com/fortunejs/fortune-json-api/blob/01644284ddeec836dcfd12b7fe2432ca557b99ad/test/index.js#L49 'cause such case doesn't work for me

**Comment by voronianski** [comment]
@daliwali 

I've got api working with filtering array value :) but still can't do anything with included related object, is it possible?

**Comment by voronianski** [comment]
@daliwali 

ok, I've got it, relations work with id query, e.g. `/articles/?include=author,category&filter[category]=4be300afbbbb1e7ff5c8bb4f76d286ba`. 👍 

Both issues were on my side. Thanks for your help!
